name: auto trigger1
on:
  push:
    branches: [ main, 'sprint/**', 'release/**', l2tets, develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**' ]
jobs:
  trigger-verification:
    uses: rdkcentral/entservices-deviceanddisplay/.github/workflows/json_validator.yml@l2test
