name: auto trigger
on:
  push:
    branches: [ develop, 'sprint/**', 'release/**', l2tets ]
  pull_request:
    branches: [ develop, 'sprint/**', 'release/**' ]

env:
  BUILD_TYPE: Debug
  THUNDER_REF: "R4.4.1"
  INTERFACES_REF: "main"
  AUTOMATICS_UNAME: ${{ secrets.AUTOMATICS_UNAME}}
  AUTOMATICS_PASSCODE: ${{ secrets. AUTOMATICS_PASSCODE}}

jobs:
  trigger-verification:
    uses: rdkcentral/entservices-testframework/.github/workflows/L2-tests.yml@l2test
