name: auto trigger1
on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', develop ]
jobs:
  trigger-verification:
    uses: entservices-testframework/.github/workflows/L2-tests.yml@l2tests
