name: L2 tests on another repo
on:
  push:
    branches: [ main, 'sprint/**', 'release/**' ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', develop ]
jobs:
  L2-tests:
     uses: rdkcentral/entservices-testframework/.github/workflows/L2-tests.yml@l2tests
     with:
         token: ${{ secrets.RDKCM_RDKE }}
     secrets:
        RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
