name: auto trigger1
on:
  push:
    branches: [ main, 'sprint/**', 'release/**', l2tets, develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', develop ]
jobs:
  trigger-verification:
     uses: rdkcentral/entservices-deviceanddisplay/.github/workflows/L2-tests.yml@l2tests
     secrets:
      RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
