name: L2 tests on another repo
on:
  push:
    branches: [ main, 'sprint/**', 'release/**' ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', develop ]
jobs:
  L2-tests:
     uses: rdkcentral/entservices-deviceanddisplay/.github/workflows/L2-tests.yml@l2tests
     secrets:
        RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
  L1-tests:
     uses: rdkcentral/entservices-deviceanddisplay/.github/workflows/L1-tests.yml@l2tests
     secrets:
        RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
