name: L2-tests-OOP

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

env:
  BUILD_TYPE: Debug
  THUNDER_REF: "R4.4.1"
  INTERFACES_REF: "main"
  AUTOMATICS_UNAME: ${{ secrets.AUTOMATICS_UNAME}}
  AUTOMATICS_PASSCODE: ${{ secrets. AUTOMATICS_PASSCODE}}

jobs:
  L2-tests-OOP:
    name: Build and run L2 tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ gcc, clang ]
        coverage: [ with-coverage, without-coverage ]
        exclude:
          - compiler: clang
            coverage: with-coverage
          - compiler: clang
            coverage: without-coverage
          - compiler: gcc
            coverage: without-coverage

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install jsonref

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'

      - name: Install packages
        run: >
          sudo apt update
          &&
          sudo apt install -y libsqlite3-dev libcurl4-openssl-dev valgrind lcov clang libsystemd-dev libboost-all-dev libwebsocketpp-dev meson libcunit1 libcunit1-dev

      - name: Install packages
        run: >
          sudo apt update
          &&
          sudo apt install -y curl protobuf-compiler-grpc libgrpc-dev libgrpc++-dev

      - name: Install GStreamer
        run: |
           sudo apt update
           sudo apt install -y libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Build trevor-base64
        run: |
            if [ ! -d "trower-base64" ]; then
            git clone https://github.com/xmidt-org/trower-base64.git
            fi
            cd trower-base64
            meson setup --warnlevel 3 --werror build
            ninja -C build
            ninja -C build install

      - name: Checkout Thunder
        uses: actions/checkout@v3
        with:
          repository: rdkcentral/Thunder
          path: Thunder
          ref: ${{env.THUNDER_REF}}

      - name: Checkout rdkservices
        uses: actions/checkout@v3
        with:
          path: rdkservices
      - name: Checkout rdkservices-apis
        uses: actions/checkout@v3
        with:
          repository: rdk-e/rdkservices-apis
          path: rdkservices-apis
          ref: ${{env.INTERFACES_REF}}
          run: rm -rf $GITHUB_WORKSPACE/rdkservices-apis/jsonrpc/DTV.json

      - name: Checkout ThunderTools
        uses: actions/checkout@v3
        with:
          repository: rdkcentral/ThunderTools
          path: ThunderTools
          ref: R4.4.3

      - name: Apply patches ThunderTools
        run: |
          cd $GITHUB_WORKSPACE/ThunderTools
          patch -p1 < $GITHUB_WORKSPACE/rdkservices/Tests/L1Tests/patches/00010-R4.4-Add-support-for-project-dir.patch
          cd -
      - name: Build ThunderTools
        run: >
          cmake
          -S "$GITHUB_WORKSPACE/ThunderTools"
          -B build/ThunderTools
          -DEXCEPTIONS_ENABLE=ON
          -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install/usr"
          -DCMAKE_MODULE_PATH="$GITHUB_WORKSPACE/install/tools/cmake"
          -DGENERIC_CMAKE_MODULE_PATH="$GITHUB_WORKSPACE/install/tools/cmake"
          &&
          cmake --build build/ThunderTools -j8
          &&
          cmake --install build/ThunderTools

      - name: Apply patch Rdkservices
        run: |
          cd $GITHUB_WORKSPACE/rdkservices
          patch -p1 < Tests/L2Tests/patches/0003-R4.4.1-SystemAudioPlayer-compilation-error.patch
          cd -

      - name: Apply patches Thunder
        run: |
          cd $GITHUB_WORKSPACE/Thunder
          patch -p1 < $GITHUB_WORKSPACE/rdkservices/Tests/L1Tests/patches/1004-Add-support-for-project-dir.patch
          patch -p1 < $GITHUB_WORKSPACE/rdkservices/Tests/L2Tests/patches/Use_Legact_Alt_Based_On_ThunderTools_R4.4.3.patch
          patch -p1 < $GITHUB_WORKSPACE/rdkservices/Tests/L2Tests/patches/error_code_R4_4.patch
          cd -
      - name: Build Thunder
        run: >
          cmake
          -S "$GITHUB_WORKSPACE/Thunder"
          -B build/Thunder
          -DMESSAGING=ON
          -DHIDE_NON_EXTERNAL_SYMBOLS=OFF
          -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install/usr"
          -DCMAKE_MODULE_PATH="$GITHUB_WORKSPACE/install/tools/cmake"
          -DBUILD_TYPE=${{env.BUILD_TYPE}}
          -DBINDING=127.0.0.1
          -DPORT=9998
          -DEXCEPTIONS_ENABLE=ON
          &&
          cmake --build build/Thunder -j8
          &&
          cmake --install build/Thunder

      - name: Copy all mock interface headers to ThunderInterfaces
        run: |
          mkdir -p "$GITHUB_WORKSPACE/rdkservices-apis/apis/IARM"
          mkdir -p "$GITHUB_WORKSPACE/rdkservices-apis/apis/Proc"
          mkdir -p "$GITHUB_WORKSPACE/rdkservices-apis/apis/RBus"
          mkdir -p "$GITHUB_WORKSPACE/rdkservices-apis/apis/Rfc"
          cp "$GITHUB_WORKSPACE/rdkservices/Tests/mocks/interfaces/IIarm.h" "$GITHUB_WORKSPACE/rdkservices-apis/apis/IARM/"
          cp "$GITHUB_WORKSPACE/rdkservices/Tests/mocks/interfaces/IProc.h" "$GITHUB_WORKSPACE/rdkservices-apis/apis/Proc/"
          cp "$GITHUB_WORKSPACE/rdkservices/Tests/mocks/interfaces/IRBus.h" "$GITHUB_WORKSPACE/rdkservices-apis/apis/RBus/"
          cp "$GITHUB_WORKSPACE/rdkservices/Tests/mocks/interfaces/IRfc.h" "$GITHUB_WORKSPACE/rdkservices-apis/apis/Rfc/"

      - name: Build rdkservices-apis
        run: >
          cmake -G Ninja
          -S "$GITHUB_WORKSPACE/rdkservices-apis"
          -B build/rdkservices-apis
          -DEXCEPTIONS_ENABLE=ON
          -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install/usr"
          -DCMAKE_MODULE_PATH="$GITHUB_WORKSPACE/install/tools/cmake"
          &&
          cmake --build build/rdkservices-apis -j8
          &&
          cmake --install build/rdkservices-apis

      - name: Generate external headers
        # Empty headers to mute errors
        run: >
          cd "$GITHUB_WORKSPACE/rdkservices/Tests/"
          &&
          mkdir -p
          headers
          headers/rdk/ds
          headers/rdk/iarmbus
          headers/rdk/iarmmgrs-hal
          headers/systemservices
          headers/systemservices/proc
          &&
          cd headers
          &&
          touch
          rdk/ds/host.hpp
          rdk/ds/videoOutputPort.hpp
          rdk/ds/audioOutputPort.hpp
          rdk/ds/sleepMode.hpp
          rdk/iarmbus/libIARM.h
          rdk/iarmbus/libIBus.h
          rdk/iarmbus/libIBusDaemon.h
          rdk/iarmmgrs-hal/mfrMgr.h
          rdk/iarmmgrs-hal/pwrMgr.h
          rdk/iarmmgrs-hal/sysMgr.h
          rfcapi.h
          rbus.h
          libudev.h
          systemservices/proc/readproc.h
          systemservices/secure_wrapper.h
          maintenanceMGR.h
          pkg.h
          &&
          cp -r /usr/include/gstreamer-1.0/gst /usr/include/glib-2.0/* /usr/lib/x86_64-linux-gnu/glib-2.0/include/* /usr/local/include/trower-base64/base64.h .

      - name: Set clang toolchain
        if: ${{ matrix.compiler == 'clang' }}
        run: echo "TOOLCHAIN_FILE=$GITHUB_WORKSPACE/rdkservices/Tests/clang.cmake" >> $GITHUB_ENV

      - name: Set gcc/with-coverage toolchain
        if: ${{ matrix.compiler == 'gcc' && matrix.coverage == 'with-coverage' && !env.ACT }}
        run: echo "TOOLCHAIN_FILE=$GITHUB_WORKSPACE/rdkservices/Tests/gcc-with-coverage.cmake" >> $GITHUB_ENV

      - name: Build mocks
        run: >
          cmake
          -S "$GITHUB_WORKSPACE/rdkservices/Tests/mocks"
          -B build/mocks
          -DBUILD_SHARED_LIBS=ON
          -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}"
          -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install/usr"
          -DCMAKE_MODULE_PATH="$GITHUB_WORKSPACE/install/tools/cmake"
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DL2_TEST_OOP_RPC=ON
          -DCMAKE_CXX_FLAGS="
          -I $GITHUB_WORKSPACE/rdkservices/Tests/headers"
          &&
          cmake --build build/mocks -j8
          &&
          cmake --install build/mocks

      - name: Build rdkservices
        run: >
          cmake
          -S "$GITHUB_WORKSPACE/rdkservices"
          -B build/rdkservices
          -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}"
          -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install/usr"
          -DCMAKE_MODULE_PATH="$GITHUB_WORKSPACE/install/tools/cmake"
          -DHIDE_NON_EXTERNAL_SYMBOLS=OFF
          -DCMAKE_CXX_FLAGS="
          -DEXCEPTIONS_ENABLE=ON
          -fprofile-arcs
          -ftest-coverage
          -DUSE_THUNDER_R4=ON
          -DTHUNDER_VERSION=4
          -DTHUNDER_VERSION_MAJOR=4
          -DTHUNDER_VERSION_MINOR=4
          -DL2_TEST_OOP_RPC=ON
          -DPLUGIN_PERSISTENTSTORE_PATH="/tmp/secure/persistent/rdkservicestore"
          -DPLUGIN_PERSISTENTSTORE_LEGACYPATH="/tmp/persistent/rdkservicestore"
          -I $GITHUB_WORKSPACE/rdkservices/Tests/headers
          -I $GITHUB_WORKSPACE/rdkservices/Tests/headers/rdk/ds
          -I $GITHUB_WORKSPACE/rdkservices/Tests/headers/rdk/iarmbus
          -I $GITHUB_WORKSPACE/rdkservices/Tests/headers/rdk/iarmmgrs-hal
          -I $GITHUB_WORKSPACE/rdkservices/Tests/headers/systemservices
          -I $GITHUB_WORKSPACE/rdkservices/Tests/headers/systemservices/proc
          -include $GITHUB_WORKSPACE/rdkservices/Tests/mocks/devicesettings.h
          -include $GITHUB_WORKSPACE/rdkservices/Tests/mocks/Iarm.h
          -include $GITHUB_WORKSPACE/rdkservices/Tests/mocks/Rfc.h
          -include $GITHUB_WORKSPACE/rdkservices/Tests/mocks/RBus.h
          -include $GITHUB_WORKSPACE/rdkservices/Tests/mocks/Udev.h
          -include $GITHUB_WORKSPACE/rdkservices/Tests/mocks/Wraps.h
          -include $GITHUB_WORKSPACE/rdkservices/Tests/mocks/maintenanceMGR.h
          -include $GITHUB_WORKSPACE/rdkservices/Tests/mocks/pkg.h
          -include $GITHUB_WORKSPACE/rdkservices/Tests/mocks/secure_wrappermock.h
          -include $GITHUB_WORKSPACE/rdkservices/Tests/mocks/wpa_ctrl_mock.h
          -include $GITHUB_WORKSPACE/rdkservices/Tests/mocks/readprocMockInterface.h
          -Werror -Wall -Wno-unused-result -Wno-deprecated-declarations -Wno-error=format=
          -DUSE_IARMBUS
          -DDISABLE_SECURITY_TOKEN
          -DENABLE_THERMAL_PROTECTION"
          -DPLUGIN_PERSISTENTSTORE_PATH="/tmp/secure/persistent/rdkservicestore"
          -DPLUGIN_PERSISTENTSTORE_LEGACYPATH="/tmp/persistent/rdkservicestore"
          -DCOMCAST_CONFIG=OFF
          -DCMAKE_DISABLE_FIND_PACKAGE_DS=ON
          -DCMAKE_DISABLE_FIND_PACKAGE_IARMBus=ON
          -DCMAKE_DISABLE_FIND_PACKAGE_Udev=ON
          -DCMAKE_DISABLE_FIND_PACKAGE_RFC=ON
          -DCMAKE_DISABLE_FIND_PACKAGE_RBus=ON
          -DPLUGIN_USERSETTINGS=OFF
          -DPLUGIN_PERSISTENTSTORE=OFF
          -DPLUGIN_POWERMANAGER=ON
          -DPLUGIN_POWERMANAGER_MODE="Local"
          -DPLUGIN_USERSETTINGS=ON
          -DPLUGIN_PERSISTENTSTORE=ON
          -DUSE_THUNDER_R4=ON
          -DPLUGIN_L2Tests=ON
          -DRDK_SERVICE_L2_TEST=ON
          -DL2_TEST_OOP_RPC=ON
          -DDS_FOUND=ON
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          &&
          cmake --build build/rdkservices -j8
          &&
          cmake --install build/rdkservices

      - name: Set up files
        run: >
          mkdir -p -m 777
          /opt/persistent
          /opt/secure
          /opt/secure/reboot
          /opt/secure/persistent
          /opt/secure/persistent/System
          /tmp/secure/persistent
          /tmp/persistent
          /tmp/persistent/rdkservicestore
          /opt/logs
          /lib/rdk
          /run/media/sda1/logs/PreviousLogs
          /run/media/sda2/logs/PreviousLogs
          /run/sda1/UsbTestFWUpdate
          /run/sda1/UsbProdFWUpdate
          /run/media/sda1/Logs
          /run/sda2
          &&
          touch
          /opt/standbyReason.txt
          /opt/tmtryoptout
          /opt/fwdnldstatus.txt
          /opt/dcm.properties
          /etc/device.properties
          /etc/dcm.properties
          /etc/authService.conf
          /version.txt
          /run/media/sda1/logs/PreviousLogs/logFile.txt
          /run/media/sda1/logs/test.txt
          /run/media/sda1/logs/test.png
          /run/media/sda1/logs/test.docx
          /run/media/sda2/logs/test.txt
          /run/media/sda2/logs/test.png
          /run/media/sda1/Logs/5C3400F15492_Logs_12-05-22-10-41PM.tgz
          /run/sda1/HSTP11MWR_5.11p5s1_VBN_sdy.bin
          /run/sda1/UsbTestFWUpdate/HSTP11MWR_3.11p5s1_VBN_sdy.bin
          /run/sda1/UsbProdFWUpdate/HSTP11MWR_4.11p5s1_VBN_sdy.bin
          /lib/rdk/getMaintenanceStartTime.sh
          /tmp/opkg.conf
          /tmp/system_service_temp.conf
          /tmp/secure/persistent/rdkservicestore
          &&
          chmod -R 777
          /opt/standbyReason.txt
          /opt/tmtryoptout
          /opt/fwdnldstatus.txt
          /opt/dcm.properties
          /etc/device.properties
          /etc/dcm.properties          
          /etc/authService.conf
          /version.txt
          /lib/rdk/getMaintenanceStartTime.sh
          /tmp/opkg.conf
          /tmp/system_service_temp.conf
          /tmp/persistent/rdkservicestore
          /tmp/secure/persistent/rdkservicestore

      - name: Download pact_verifier_cli
        run: >
          echo "Copying pact plugins" &&
          PATH=$GITHUB_WORKSPACE/install/usr/bin:${PATH}
          $GITHUB_WORKSPACE/rdkservices/Tests/L2Tests/pact/install-verifier-cli.sh

      - name: Run unit tests without valgrind
        run: >
          PATH=$GITHUB_WORKSPACE/install/usr/bin:${PATH}
          LD_LIBRARY_PATH=$GITHUB_WORKSPACE/install/usr/lib:$GITHUB_WORKSPACE/install/usr/lib/wpeframework/plugins:${LD_LIBRARY_PATH}
          RdkServicesL2Test &&
          cp -rf $(pwd)/rdkL2TestResults.json $GITHUB_WORKSPACE/rdkL2TestResultsWithoutValgrind.json &&
          rm -rf $(pwd)/rdkL2TestResults.json

      - name: Run unit tests with valgrind
        if: ${{ !env.ACT }}
        run: >
          PATH=$GITHUB_WORKSPACE/install/usr/bin:${PATH}
          LD_LIBRARY_PATH=$GITHUB_WORKSPACE/install/usr/lib:$GITHUB_WORKSPACE/install/usr/lib/wpeframework/plugins:${LD_LIBRARY_PATH}
          valgrind
          --tool=memcheck
          --log-file=valgrind_log
          --leak-check=yes
          --show-reachable=yes
          --track-fds=yes
          --fair-sched=try
          RdkServicesL2Test &&
          cp -rf $(pwd)/rdkL2TestResults.json $GITHUB_WORKSPACE/rdkL2TestResultsWithValgrind.json &&
          rm -rf $(pwd)/rdkL2TestResults.json
          
      - name: Generate coverage
        if: ${{ matrix.coverage == 'with-coverage' && !env.ACT }}
        run: >
          cp $GITHUB_WORKSPACE/rdkservices/Tests/L2Tests/.lcovrc_l2 ~/.lcovrc
          &&
          lcov -c
          -o coverage.info
          -d build/rdkservices
          &&
          lcov
          -r coverage.info
          '/usr/include/*'
          '*/build/rdkservices/_deps/*'
          '*/install/usr/include/*'
          '*/Tests/headers/*'
          '*/Tests/mocks/*'
          '*/Tests/L2Tests/*'
          -o filtered_coverage.info
          &&
          genhtml
          -o coverage
          -t "rdkservices coverage"
          filtered_coverage.info

      - name: Upload artifacts
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            coverage/
            valgrind_log
            rdkL2TestResultsWithoutValgrind.json
            rdkL2TestResultsWithValgrind.json
          if-no-files-found: warn

      - name: Set up JFrog CLI
        if: ${{ !env.ACT }}
        uses: jfrog/setup-jfrog-cli@v1

      - name: Configure JFrog CLI
        if: ${{ !env.ACT }}
        run: |
          jfrog config add Default-Server --artifactory-url "https://${{ vars.DOCKER_REGISTRY }}/artifactory" \
          --user "${{ vars.RDKE_ARTIFACTORY_USER }}" \
          --apikey "${{ secrets.RDKE_ARTIFACTORY_USER_APIKEY }}" \
          --interactive=false

      - name: Download Package from Artifactory
        if: ${{ !env.ACT }}
        run: |
          mkdir -p ~/downloadsforartifactory/
          jfrog rt dl "${{vars.SKY_IUI_ARTIFACTORY_PATH}}pact_websocket_plugin/0.4.2/_/4dc638bc20b75a06659b2238715e0e9e/package/b647c43bfefae3f830561ca202b6cfd935b56205/8ac9efcc0f7c26c31fce8b6a715f8c3d/conan_package.tgz" ~/downloadsforartifactory/ --flat=true

      - name: Extract the downloaded package
        if: ${{ !env.ACT }}
        run: |
          mkdir -p ~/.pact/plugins/
          mkdir -p $GITHUB_WORKSPACE/rdkservices/Tests/L2Tests/pact/websockets-0.4.2/
          tar -xzvf ~/downloadsforartifactory/conan_package.tgz -C $GITHUB_WORKSPACE/rdkservices/Tests/L2Tests/pact/websockets-0.4.2/
          cp -r $GITHUB_WORKSPACE/rdkservices/Tests/L2Tests/pact/websockets-0.4.2/plugins/* ~/.pact/plugins/

      - name: Run contract tests
        if: ${{ !env.ACT }}
        env:
          PACTFLOW_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
        run: >
          PATH=$GITHUB_WORKSPACE/install/usr/bin:${PATH}
          LD_LIBRARY_PATH=$GITHUB_WORKSPACE/install/usr/lib:$GITHUB_WORKSPACE/install/usr/lib/wpeframework/plugins:${LD_LIBRARY_PATH}
          RdkServicesL2Test GenerateJsonOutputNotRequired CTVerifierMain

      - name: Upload contract test results
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: Contract test results
          path: |
            contract-test-results.json
            contract-test-statistics.txt
          if-no-files-found: warn

      - name: Coping results to /tmp/Gtest_Report/
        if: ${{ !env.ACT }}
        run: >
          mkdir -p /tmp/Gtest_Report/ &&
          cp -r valgrind_log rdkL2TestResultsWithoutValgrind.json rdkL2TestResultsWithValgrind.json coverage /tmp/Gtest_Report/

      - name: Publishing the artifacts to automatics
        if: ${{ !env.ACT }}
        run: >
          git config --global --add safe.directory `pwd`/rdkservices &&
          gtest-json-result-push.py /tmp/Gtest_Report https://rdkeorchestrationservice.apps.cloud.comcast.net/rdke_orchestration_api/push_unit_test_results `pwd`/rdkservices
